// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1cpByXneAvDO4c_1qZBgrPByWgB9peKk',
    appId: '1:677692034640:web:a82421615b8c7ea77c4b55',
    messagingSenderId: '677692034640',
    projectId: 'android-class-73857',
    authDomain: 'android-class-73857.firebaseapp.com',
    storageBucket: 'android-class-73857.appspot.com',
    measurementId: 'G-ZZVH3YRJBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi_eA00A-UXEpQFEjqHqrWfQK3QMd1ydw',
    appId: '1:677692034640:android:0ef6b96d277c5a0f7c4b55',
    messagingSenderId: '677692034640',
    projectId: 'android-class-73857',
    storageBucket: 'android-class-73857.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJvekGVjmmJGcoVBJreadjTTdNrqpKeR4',
    appId: '1:677692034640:ios:a71efb7bffbbf66c7c4b55',
    messagingSenderId: '677692034640',
    projectId: 'android-class-73857',
    storageBucket: 'android-class-73857.appspot.com',
    iosBundleId: 'com.example.androidClass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJvekGVjmmJGcoVBJreadjTTdNrqpKeR4',
    appId: '1:677692034640:ios:03eece430631548a7c4b55',
    messagingSenderId: '677692034640',
    projectId: 'android-class-73857',
    storageBucket: 'android-class-73857.appspot.com',
    iosBundleId: 'com.example.androidClass.RunnerTests',
  );
}
